version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/packages/core-env"
      - "/packages/core-env-azurekv"
      - "/packages/core-env-container"
      - "/packages/core-env-dotenv"
      - "/packages/core-env-fetch"
      - "/packages/core-env-nodejs"
      - "/packages/core-env-tachyon"
      - "/packages/core-env-vite"
      - "/packages/core-env-secretspec"
    schedule:
      interval: "weekly"
    groups:
      dev-dependencies:
        dependency-type: "development"
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]