version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/packages/core-env"
      - "/packages/core-env-azurekv"
      - "/packages/core-env-container"
      - "/packages/core-env-dotenv"
      - "/packages/core-env-fetch"
      - "/packages/core-env-nodejs"
      - "/packages/core-env-tachyon"
      - "/packages/core-env-vite"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "*"
        dependency-type: "production"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]