[project]
name = "my-app"
revision = "1.0"

[profiles.default]
DATABASE_URL = { description = "PostgreSQL connection string", required = true }
SQLITE_URL = { description = "PostgreSQL connection string", default = "sqlite://./dev.db" }

[profiles.development]
DATABASE_URL = { description = "PostgreSQL connection string", default = "sqlite://./dev.db" }

[profiles.production]
DATABASE_URL = { description = "PostgreSQL connection string", default = "sqlite://./dev.db" }