name: core-env-fetch CI
on:
  push:
    branches: [main]
    paths:
      - "packages/core-env-fetch/**"
      - ".github/workflows/core-env-fetch.yml"
      - ".github/workflows/module.yml"

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  module-flow:
    uses: ./.github/workflows/module.yml
    with:
      package-path: packages/core-env-fetch
